### ISSUE TITLE
Code link correction

### ISSUE THREAD

**Issue by YuejiangLIU** [colorfulfuture/Awesome-Trajectory-Motion-Prediction-Papers#1]
Hi Yi,

Thanks for making the curated paper list public.

The code for our paper `Towards Robust and Adaptive Motion Forecasting: A Causal Representation Perspective` is split into two repositories. In the current paper list, the code link actually corresponds to our secondary repo.

Could you please replace it with the primary repo (https://github.com/vita-epfl/causalmotion)? 

Thanks,
Yuejiang

**Comment by colorfulfuture** [comment]
Hi Yuejiang,

Thank you for staring this paper list.  Sorry about the mistake, I just replaced the original link with the primary one. It's an excellent work, I discussed with Riccardo Cadei in New Orleans, and this inspired me a lot.

Best,
Yi

**Comment by YuejiangLIU** [comment]
Thank you, Yi, for updating the link :)
