### ISSUE TITLE
Ask if your work Adapting to Length Shift: FlexiLength Network for Trajectory Prediction will be open sourced 

### ISSUE THREAD

**Issue by zachytong** [colorfulfuture/Awesome-Trajectory-Motion-Prediction-Papers#34]
Hi dear Xu Yi, 

Congratulations for the acceptance of your great work Adapting to Length Shift: FlexiLength Network for Trajectory Prediction work! The topic is to the ground and closely related to the application and deployment of trajectory prediction models, and may I ask if you have any plan to open source it?

Also thanks for your previous works and this repository, they helps a lot!!! Hope everything goes on well with your research : )

Best wish!

zachy

**Comment by colorfulfuture** [comment]
Hi Zachy,

Thank you so much for your continuous contribution to this repo!

Yes, I plan to release the codes but I am too busy. It may take some time.

Best,
Yi
